/* EGA110 Glossary Data — all terms across all topics */

const glossaryData = {
  t1: {
    name: "Topic 1 — Measurements: Data & Errors",
    terms: [
      ["Analytical chemistry","The science that develops and applies methods, instruments, and strategies to obtain information on the composition and nature of matter"],
      ["Accuracy","How close a measured value is to the true (accepted) value. Measured by absolute or relative error — NOT by standard deviation"],
      ["Precision","How close replicate measurements are to one another. Measured by standard deviation — NOT by error relative to a true value"],
      ["Random (indeterminate) error","Unpredictable errors that affect precision; caused by uncontrollable variables; lead to scatter about the mean. Cannot be eliminated, only reduced by averaging. Affects the last significant figure"],
      ["Systematic (determinate) error","Consistent, repeatable errors that always shift results in the same direction. Affect accuracy. Can in principle be identified and corrected. Sources: instrumental, methodological, personal, environmental"],
      ["Gross error","Occasional large mistakes that produce outliers far outside the expected scatter range. Often discarded using the Q-test"],
      ["True value (x_t)","The accepted correct value of the measured quantity. Used to calculate absolute and relative error. Often a certified reference material value"],
      ["Absolute error (E_i)","E_i = |x_i − x_t|. Difference between measured and true values. Same units as the measurement"],
      ["Relative error (R_i)","R_i = |x_i − x_t| / x_t. Absolute error divided by true value; dimensionless (or %). Allows comparison across different measurement scales"],
      ["Significant figures","Number of meaningful digits in a measurement, reflecting its precision. Arithmetic rules: addition/subtraction → fewest decimal places; multiplication/division → fewest sig figs"],
      ["Population mean (μ)","μ = Σxᵢ / N. True average of the entire population of measurements. Usually unknown — estimated by sample mean x̄"],
      ["Sample mean (x̄)","x̄ = Σxᵢ / N. Arithmetic average of N replicate measurements. Best estimate of population mean μ"],
      ["Population standard deviation (σ)","σ = √[Σ(xᵢ − μ)² / N]. Spread of the entire population. Usually unknown"],
      ["Sample standard deviation (s)","s = √[Σ(xᵢ − x̄)² / (N−1)]. Spread of sample measurements. Uses N−1 (Bessel's correction) to give unbiased estimate of σ"],
      ["Standard error of the mean (S_m)","S_m = s / √N. Uncertainty in the sample mean; decreases as N increases. Quantifies how precisely x̄ estimates μ"],
      ["Relative standard deviation (RSD)","RSD = (s / x̄) × 100%. Also called coefficient of variation (CV). Expresses precision as a percentage of the mean"],
      ["Gaussian (normal) distribution","Bell-shaped symmetric probability distribution describing scatter of random errors. Defined by μ and σ. Used to calculate probabilities of measurement outcomes"],
      ["68-95-99.7 rule","For a Gaussian: ~68% of data within ±1σ, ~95% within ±2σ, ~99.7% within ±3σ of the mean"],
      ["Median","Middle value when data sorted in order. More robust than mean in the presence of outliers"],
      ["Instrumental error","Systematic error from uncalibrated or drifting instruments: zero offsets, temperature-affected electronics, worn components"],
      ["Methodological error","Systematic error from flawed procedure: incorrect sampling, incomplete reactions, matrix interference, indicator end point error"],
      ["Personal error","Systematic error from observer bias or technique: always reading burette above or below meniscus, parallax error"],
    ]
  },
  t2: {
    name: "Topic 2 — Statistical Data Analysis",
    terms: [
      ["Confidence interval (CI)","Range of values within which the true mean μ is expected to lie with a given probability. CI = x̄ ± zσ/√N (σ known) or x̄ ± ts/√N (σ unknown)"],
      ["Confidence level","The probability (e.g. 95%) that the true mean lies within the calculated CI. Higher level → wider CI. Commonly 90%, 95%, 99%"],
      ["z-statistic","Multiplier in CI calculation when population σ is known. z₉₅ = 1.96; z₉₉ = 2.58; z₉₀ = 1.64. Gives narrower CI than t at same confidence level"],
      ["t-statistic","Multiplier in CI when σ is unknown (small sample). Depends on df = N−1. Always larger than z; accounts for additional uncertainty from estimating σ"],
      ["Degrees of freedom (df)","df = N−1 for one sample; df = N₁+N₂−2 for two-sample comparison. Determines which t-value to use from the table"],
      ["Pooled standard deviation (s_pooled)","Combined SD from k datasets: s_pooled = √[Σ(Nᵢ−1)sᵢ²/(ΣNᵢ−k)]. Used as estimate of σ for CI or two-means test when all datasets have similar spread"],
      ["Null hypothesis","Assumption tested statistically, e.g. 'two means are equal' or 'there is no systematic error'. Rejected if test statistic exceeds critical value at chosen confidence level"],
      ["Type I error (false positive)","Incorrectly rejecting a true null hypothesis. Probability = α = (1 − confidence level). Lower α requires higher critical value → harder to reject null"],
      ["Two-means comparison test","Statistical test for significant difference. Reject null if: |x̄₁ − x̄₂| > t × s_pooled × √[(N₁+N₂)/(N₁×N₂)]. df = N₁+N₂−2"],
      ["Bias detection test","Tests for systematic error by comparing x̄ to known true value x_t. Reject null (no bias) if: |x̄ − x_t| > t × s/√N"],
      ["Q-test (Dixon's test)","Outlier test. Q = gap / range = |x_q − nearest_neighbour| / total_spread. Reject if Q > Q_critical (from table). Sort data ascending first"],
      ["Outlier","A measurement significantly inconsistent with the rest of the dataset. Must be tested (Q-test) before discarding — never discard without justification"],
      ["Q-test critical values (90% CL)","N=3: 0.941; N=4: 0.765; N=5: 0.642; N=6: 0.560; N=7: 0.507; N=8: 0.468; N=9: 0.437; N=10: 0.412"],
      ["s_pooled usage rule","s_pooled can be used as σ estimate when: (1) all component datasets have statistically similar standard deviations, and (2) total pooled df is large (e.g. ≥25)"],
      ["Statistical significance","A result is statistically significant at a given confidence level if the probability of observing it by chance (under null hypothesis) is less than α = (1 − CL)"],
    ]
  },
  t3: {
    name: "Topic 3 — Gravimetric Analysis",
    terms: [
      ["Gravimetric analysis","Quantitative analytical method based on measurement of mass. Analyte is isolated and the mass of a precisely characterised compound is measured"],
      ["Precipitation gravimetry","Most common type. Analyte converted to insoluble precipitate by adding precipitating agent; filtered, dried/ignited, weighed"],
      ["Volatilisation gravimetry","Mass change measured when a volatile component (CO₂, H₂O, SO₂) is released. Either direct (mass loss measured) or collection (volatile absorbed in weighed trap)"],
      ["Electrogravimetry","Analyte electrodeposited onto pre-weighed platinum electrode by controlled potential; mass of deposited metal determined by mass gain"],
      ["Thermogravimetric analysis (TGA)","Mass recorded continuously as sample is heated at controlled rate (e.g. 10°C/min). Mass-loss steps reveal decomposition temperatures and identify compounds"],
      ["Derivative TGA (DTG)","First derivative of TGA; peaks mark temperature of maximum mass-loss rate; separates overlapping decomposition events"],
      ["Precipitating agent","Reagent added to convert analyte to insoluble precipitate. Common agents: AgNO₃ (for Cl⁻, Br⁻, I⁻), BaCl₂ (for SO₄²⁻), ammonium oxalate (for Ca²⁺), DMG (for Ni²⁺)"],
      ["Gravimetric factor (GF)","GF = (a × MM_analyte)/(b × MM_precipitate). Converts mass of precipitate to mass of analyte. Must include stoichiometric coefficients a and b"],
      ["8 steps of precipitation gravimetry","1-Weigh sample, 2-Dissolve, 3-Precipitate analyte, 4-Filter, 5-Wash precipitate, 6-Dry or ignite, 7-Weigh, 8-Calculate analyte amount from precipitate mass"],
      ["Digestion","Heating precipitate in mother liquor after formation to improve crystal size via Ostwald ripening; reduces surface area, removes occluded impurities"],
      ["Ostwald ripening","Dissolution of smaller crystals and redeposition on larger ones; driven by lower solubility of larger crystals; improves precipitate purity and filterability"],
      ["Coprecipitation","Contamination of precipitate by unwanted species. Four types: surface adsorption, occlusion, mechanical entrapment, post-precipitation"],
      ["Surface adsorption","Ions from solution adsorb onto crystal surface; minimised by washing with appropriate wash solution"],
      ["Occlusion","Impurities physically trapped within crystal during growth; cannot be removed by washing; minimised by slow precipitation"],
      ["Mechanical entrapment","Mother liquor physically trapped within precipitate; minimised by digestion and proper filtration"],
      ["Post-precipitation","Second precipitate nucleates and grows on surface of primary precipitate during prolonged standing in mother liquor"],
      ["Mother liquor","Solution surrounding the precipitate during and after precipitation. Contains excess precipitating agent and dissolved impurities"],
      ["Combustion analysis","Organic sample burned in excess O₂; H₂O trapped in Drierite, CO₂ trapped in Ascarite; mass gains give n(H) and n(C)"],
      ["Drierite (CaSO₄)","Drying agent/H₂O absorbent in combustion analysis. Mass gain = m(H₂O) → n(H₂O) → n(H)"],
      ["Ascarite (NaOH on silica)","CO₂ absorbent in combustion analysis. Mass gain = m(CO₂) → n(CO₂) → n(C)"],
      ["Calcination","Heating dried precipitate to high temperature to decompose it to a stable stoichiometric form of known composition"],
      ["Empirical formula determination","From %C, %H, %O (and metals): calculate n of each element, divide by smallest, round to integers or simple ratio"],
    ]
  },
  t4: {
    name: "Topic 4 — Spectroscopy",
    terms: [
      ["Electromagnetic radiation (EMR)","Energy propagated as oscillating electric and magnetic fields perpendicular to each other and to the direction of propagation. Both wave and particle nature"],
      ["Wavelength (λ)","Distance between successive wave crests. Units: m, cm, nm. c = λυ"],
      ["Frequency (υ)","Number of oscillations per second. Units: Hz = s⁻¹. Does NOT change when light moves between media (unlike λ and v)"],
      ["Wavenumber (ν̄)","ν̄ = 1/λ (cm⁻¹). Proportional to energy. Used in IR spectroscopy. When λ in nm: ν̄(cm⁻¹) = 10⁷/λ(nm)"],
      ["Speed of light (c)","c = 2.998×10⁸ m s⁻¹ in vacuum. Changes in media (v = c/n); wavelength changes but frequency and energy remain constant"],
      ["Photon energy (E)","E = hυ = hc/λ = hcν̄. Planck's constant h = 6.626×10⁻³⁴ J s. Higher frequency → shorter wavelength → higher energy"],
      ["Planck's constant (h)","h = 6.626×10⁻³⁴ J Hz⁻¹. Links energy of a photon to its frequency: E = hυ"],
      ["Radiation intensity (I)","I = P/A = EΦ/A where P = power (W), A = cross-sectional area, Φ = photon flux (photons/s). Units: W m⁻² or W μm⁻²"],
      ["Transmittance (T)","T = I/I₀. Fraction of incident intensity transmitted through sample. T = 1 (no absorption), T = 0 (complete absorption)"],
      ["Percent transmittance (%T)","%T = (I/I₀) × 100. Note: A = −log(T) = −log(%T/100) = 2 − log(%T)"],
      ["Absorbance (A)","A = −log T = log(I₀/I) = εbc. Dimensionless. Directly proportional to concentration. Additive for multiple absorbers"],
      ["Beer-Lambert law","A = εbc. Holds for monochromatic light and dilute solutions. Deviations at high c from self-absorption, refractive index changes, chemical equilibria"],
      ["Molar absorptivity (ε)","ε in Beer-Lambert law. Units: L mol⁻¹ cm⁻¹. Species, solvent, and wavelength specific. Maximum at λ_max"],
      ["Path length (b)","Length of sample traversed by light. Units: cm in Beer-Lambert law. Usually 1 cm cuvette"],
      ["λ_max","Wavelength of maximum molar absorptivity. Best wavelength to measure: highest sensitivity; Beer-Lambert most linear here"],
      ["Blank correction","Measured intensity through blank (solvent only) used as I_B reference. A_analyte = −log(I_A/I_B). Removes background contributions from solvent and cuvette"],
      ["Standard addition method","Add known spike of standard to unknown sample: C_analyte = A_analyte/(A_spiked − A_analyte) × C_spike. Compensates for matrix effects. Used when matrix cannot be replicated"],
      ["Direct comparison (method B/C)","C_analyte = (A_analyte / A_std) × C_std. Cancels ε and b. Requires identical conditions for sample and standard"],
      ["Known ε method (method A)","C = A/(εb). Requires accurate knowledge of ε. Quick but requires well-characterised standard conditions"],
      ["Matrix effect","Influence of sample components other than the analyte on measurement. Standard addition compensates; external calibration may not"],
      ["Ground state","Lowest energy electronic state of an atom/molecule. Electrons occupy ground state at room temperature"],
      ["Excited state","Higher energy state reached when atom absorbs photon of energy exactly = ΔE between states. Quantised — only discrete energies allowed"],
      ["Absorption","Photon absorbed and atom/molecule promoted to excited state. Occurs when photon energy = ΔE. Basis of UV/Vis spectrophotometry"],
      ["Emission","Excited atom/molecule releases photon and returns to lower energy state. Basis of atomic emission spectroscopy"],
      ["Fluorescence","Rapid radiative emission after absorption. Spin-allowed → lifetime ~ns. Emitted photon has same or longer wavelength than absorbed"],
      ["Phosphorescence","Delayed radiative emission. Spin-forbidden transition → lifetime ms to s. Used in glow-in-the-dark materials"],
      ["Non-radiative relaxation","Energy dissipated as heat instead of photon. Competes with fluorescence/phosphorescence. Why quantum yield < 1"],
      ["Deuterium lamp","UV source (150–400 nm). Continuous spectrum. Standard in UV-Vis spectrophotometers for UV region"],
      ["Tungsten-halogen lamp","Visible source (400–800 nm). Continuous blackbody spectrum at ~3500 K. Standard for Vis measurements"],
      ["Diffraction grating","Wavelength selector. Disperses light by diffraction: nλ = d sinθ. Tunable by rotation — select any wavelength"],
      ["Quartz cuvette","Transparent to UV and Vis (160–3000 nm). Required for UV measurements. Glass/plastic only transmit Vis"],
      ["Photomultiplier tube (PMT)","Highly sensitive photon detector. Cascade of dynodes amplifies signal ~10⁶×. Range 150–1000 nm"],
      ["Single-beam spectrometer","Blank and sample measured sequentially through same light path. Simpler; susceptible to source drift between measurements"],
      ["Double-beam spectrometer","Beam split between sample and reference paths simultaneously. Compensates source fluctuation; more accurate"],
      ["Nebulisation","Breaking solution into fine aerosol for introduction into flame/plasma. First step in solution-based atomic spectroscopy"],
      ["Desolvation","Evaporation of solvent from aerosol droplets; produces dry solid particles before atomisation"],
      ["Atomisation","Vaporisation and dissociation of solid particles to free gas-phase atoms. Required for atomic absorption/emission"],
      ["ICP-OES","Inductively Coupled Plasma Optical Emission Spectroscopy. RF-induced Ar plasma (6000–10,000 K). Multi-element; wide dynamic range (0.01–500 µg/mL)"],
      ["Flame emission spectroscopy (FES)","Flame (1700–3000 K) excites atoms; simpler, less sensitive than ICP-OES. Best for alkali metals (Na, K, Li)"],
      ["Self-absorption","At high analyte concentrations, emitted photons are reabsorbed by ground-state atoms of the same element → non-linearity in emission calibration"],
      ["Calibration curve","Plot of instrument response vs known concentration for a series of standards. Interpolate to find unknown concentration"],
      ["Wave-particle duality","EMR behaves as wave (diffraction, interference) and particle/photon (photoelectric effect, discrete absorption/emission)"],
    ]
  },
  t5: {
    name: "Topic 5 — Titrations in Analytical Chemistry",
    terms: [
      ["Titrimetric analysis (titration)","Determining analyte amount by measuring volume of standard titrant required for stoichiometric reaction"],
      ["Titrant","Reagent of precisely known concentration added from a burette"],
      ["Analyte (titrand)","The species being determined"],
      ["Equivalence point (EQ)","Point where stoichiometric amount of titrant has been added. Theoretical — not directly observable"],
      ["End point (EP)","Experimentally observed signal change (colour, pH, conductivity) marking the titration termination. Should be close to EQ"],
      ["Titration error","E_t = V_EP − V_EQ. Positive = overtitrated; negative = undertitrated"],
      ["4 titration types","1-Neutralisation (acid-base), 2-Complexometric, 3-Precipitation, 4-Redox"],
      ["pH","pH = −log[H₃O⁺]. Acidity measure. pH + pOH = 14 at 25°C"],
      ["Ion product of water (Kw)","Kw = [H₃O⁺][OH⁻] = 1.0×10⁻¹⁴ at 25°C, 1 bar. Relates pH and pOH"],
      ["Strong acid","Completely dissociates in water: HCl, HNO₃, H₂SO₄, HClO₄. [H₃O⁺] = C_acid"],
      ["Strong base","Completely dissociates in water: NaOH, KOH. [OH⁻] = C_base"],
      ["Weak acid (HA)","Partially dissociates: HA ⇌ H⁺ + A⁻. Ka = [H⁺][A⁻]/[HA]. pKa = −log Ka"],
      ["Weak base (A⁻)","Partially accepts proton: A⁻ + H₂O ⇌ HA + OH⁻. Kb = Kw/Ka. pKb = −log Kb"],
      ["Henderson-Hasselbalch equation","pH = pKa + log([A⁻]/[HA]). Buffer region calculation. At half-equivalence point: [A⁻]=[HA] → pH = pKa"],
      ["Half-equivalence point","V_BOH = ½ V_EQ. pH = pKa (weak acid) or pH = 14 − pKb (weak base). Maximum buffering capacity point"],
      ["Buffer","Solution resisting pH change. Contains weak acid HA and conjugate base A⁻ (or weak base + its conjugate acid). Role in EDTA titrations: maintain pH for complexation and indicator colour"],
      ["Indicator","Weak acid/base whose acid and base forms have different colours. Colour change at pKa ± 1. Must overlap EQ pH"],
      ["Phenolphthalein","pKa 9.5; colourless (acid) → pink (base); pH 8.5–10.5. Use for weak acid/strong base or strong acid/strong base titrations"],
      ["Bromothymol blue","pKa 7.3; yellow (acid) → blue (base); pH 6.3–8.3. Suitable for near-neutral equivalence points"],
      ["Methyl red","pKa 5.0; red (acid) → yellow (base); pH 4.0–6.0"],
      ["Bromophenol blue","pKa 4.1; yellow (acid) → blue-violet (base); pH 3.1–5.1. Use for very strong acid titrations"],
      ["Equivalence point pH (strong/strong)","pH = 7 at 25°C. Neutral salt solution formed"],
      ["Equivalence point pH (weak acid/strong base)","pH > 7 — conjugate base (A⁻) is weakly basic. pH = −log√(Kw × Ka / C_AB)"],
      ["Polyprotic acid","Multiple ionisable protons; multiple equivalence points. H₃PO₄: pKa1=2.16, pKa2=7.21, pKa3=12.32. Each midpoint pH = corresponding pKa"],
      ["Complexometric titration","Metal ion titrated with chelating ligand to form stable complex. pM monitored; colour change of metalloind indicator marks endpoint"],
      ["Chelate effect","Polydentate ligands form more stable complexes than equivalent monodentate ligands. Driven by positive entropy change (Δn molecules released) when multidentate ligand displaces monodentate waters"],
      ["Denticity","Number of donor atoms in a ligand that simultaneously bind to the metal ion. Mono(1), bi(2), tetra(4), hexa(6)"],
      ["Formation constant (Kf / KMY)","Kf = [ML]/([M][L]). Stability constant of metal-ligand complex. Large Kf → very stable. EDTA Kf values: Ca²⁺ = 5×10¹⁰; Fe³⁺ = 1.3×10²⁵"],
      ["Overall stability constant (βn)","βn = K₁×K₂×···×Kn = [MLn]/([M][L]^n). Product of all stepwise formation constants"],
      ["EDTA (ethylenediaminetetraacetic acid, H₄Y)","Hexadentate ligand: 2 N + 4 O donor atoms. Most widely used complexing titrant. Reacts 1:1 with ALL metal ions regardless of charge"],
      ["Y⁴⁻ (fully deprotonated EDTA)","Active form of EDTA that complexes metal ions. M^n+ + Y⁴⁻ → MY^(n−4)+. Dominant above pH 10"],
      ["EDTA 1:1 ratio","EDTA always reacts 1:1 with metal cations regardless of charge — Ag⁺, Ca²⁺, Fe³⁺, Th⁴⁺ all react with 1 mole Y⁴⁻"],
      ["Eriochrome Black T (EBT)","Metallochromic indicator for Ca²⁺/Mg²⁺ EDTA titrations at pH 10. Metal-EBT = red; free EBT = blue. Endpoint: red → blue. Must be pH > 6.3"],
      ["Xylenol orange (XO)","Indicator for Zn²⁺, Ga³⁺, Pb²⁺, Bi³⁺ at pH 4–6. ZnXO = red/pink; free XO at pH 5.7 = yellow. Endpoint: red → yellow"],
      ["Solubility product (Ksp)","Ksp = [A]^a[B]^b for A_aB_b(s) ⇌ aA(aq) + bB(aq). Small Ksp → sparingly soluble. Applies only when solid is present"],
      ["Argentometric titration","Precipitation titration using AgNO₃. Precipitates Cl⁻ (Ksp AgCl = 1.8×10⁻¹⁰), Br⁻ (5.3×10⁻¹³), I⁻ (8.5×10⁻¹⁷)"],
      ["Volhard method","Back-titration for halides. Excess AgNO₃ added → AgX precipitated → filtered → excess Ag⁺ back-titrated with KSCN; Fe³⁺ indicator → FeSCN²⁺ (red) at endpoint"],
      ["Back-titration","Add known excess of primary reagent; titrate excess with a second standard. Used when direct endpoint is difficult"],
      ["Conductometry (titration endpoint)","Electrical conductivity monitored; V-shaped minimum indicates EQ in precipitation titrations. σ = 1/ρ (S cm⁻¹)"],
      ["Standard reduction potential (E⁰)","Tendency of species to be reduced vs SHE (= 0 V). More positive → stronger oxidising agent. Reaction spontaneous when E⁰_rxn = E⁰_red − E⁰_ox > 0"],
      ["Redox half-reaction","Either oxidation (electron loss) or reduction (electron gain). Must be balanced separately then combined with equalised electrons"],
      ["KMnO₄/Fe²⁺ titration","MnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O. Ratio 1:5. E⁰_rxn = +0.74 V. Self-indicating: endpoint = first permanent purple. Run in H₂SO₄"],
      ["Dichromate/Fe²⁺ titration","Cr₂O₇²⁻ + 6Fe²⁺ + 14H⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O. Ratio 1:6. Diphenylamine sulfonate indicator (colourless → blue-green at endpoint)"],
      ["Self-indicating titrant","Titrant that produces its own colour change at excess; no separate indicator needed. KMnO₄ (purple) is the prime example"],
      ["Diphenylamine sulfonate","Redox indicator for dichromate titrations. Colourless in reduced form → blue-green when oxidised by excess Cr₂O₇²⁻"],
    ]
  }
}
