/* EGA110 Glossary Data — all terms across all topics */

const glossaryData = {
  t1: {
    name: "Topic 1 — Measurements: Data & Errors",
    terms: [
      ["Analytical chemistry","Science of developing and applying methods to determine the composition and nature of matter"],
      ["Accuracy","Closeness of a measurement to the true value \\(x_t\\). Measured by error — NOT by standard deviation"],
      ["Precision","Closeness of replicate measurements to each other. Measured by standard deviation — NOT by error"],
      ["Random (indeterminate) error","Unpredictable scatter from uncontrollable variables. Affects precision; reduced by averaging. Affects the last significant figure"],
      ["Systematic (determinate) error","Consistent bias always in one direction. Affects accuracy; can in principle be identified and corrected"],
      ["Gross error","Large isolated mistake producing an outlier far outside normal scatter. Test with Q-test before discarding"],
      ["True value (x_t)","The accepted correct value of the measured quantity \\(x_t\\). Often the value of a certified reference material"],
      ["Absolute error","\\(E_i = |x_i - x_t|\\). Difference between measured and true values; same units as the measurement"],
      ["Relative error","\\(R_i = |x_i - x_t| / x_t\\). Dimensionless; multiply ×100 for %"],
      ["Significant figures","Digits reflecting measurement precision. Addition/subtraction: fewest decimal places. Multiplication/division: fewest sig figs"],
      ["Population mean (μ)","\\(\\mu = \\sum x_i / N\\). True average of all measurements; usually unknown — estimated by \\(\\bar{x}\\)"],
      ["Sample mean (x̄)","\\(\\bar{x} = \\sum x_i / N\\). Arithmetic average of N replicates; best estimate of \\(\\mu\\)"],
      ["Population standard deviation (σ)","\\(\\sigma = \\sqrt{\\sum(x_i - \\mu)^2 / N}\\). Spread of the entire population; usually unknown"],
      ["Sample standard deviation (s)","\\(s = \\sqrt{\\sum(x_i - \\bar{x})^2 / (N-1)}\\). Uses \\(N-1\\) (Bessel's correction) for unbiased estimate of \\(\\sigma\\)"],
      ["Standard error of the mean (S_m)","\\(S_m = s / \\sqrt{N}\\). Uncertainty in \\(\\bar{x}\\); decreases as N increases"],
      ["Relative standard deviation (RSD)","\\(\\text{RSD} = (s / \\bar{x}) \\times 100\\%\\). Also called coefficient of variation (CV)"],
      ["Gaussian (normal) distribution","Bell-shaped distribution describing scatter of random errors. Defined by \\(\\mu\\) and \\(\\sigma\\)"],
      ["68-95-99.7 rule","For a Gaussian: 68% within ±1\\(\\sigma\\), 95% within ±2\\(\\sigma\\), 99.7% within ±3\\(\\sigma\\) of the mean"],
      ["Median","Middle value when data are sorted. More robust than the mean when outliers are present"],
      ["Instrumental error","Systematic error from uncalibrated or drifting instruments (zero offsets, temperature drift, worn parts)"],
      ["Methodological error","Systematic error from a flawed procedure: incorrect sampling, incomplete reactions, matrix interference"],
      ["Personal error","Systematic error from observer bias: consistently reading above/below the meniscus, parallax"],
    ]
  },
  t2: {
    name: "Topic 2 — Statistical Data Analysis",
    terms: [
      ["Confidence interval (CI)","Range likely containing the true mean \\(\\mu\\). \\(\\text{CI} = \\bar{x} \\pm z\\sigma/\\sqrt{N}\\) (σ known) or \\(\\bar{x} \\pm ts/\\sqrt{N}\\) (σ unknown)"],
      ["Confidence level","Probability (e.g. 95%) that the CI contains \\(\\mu\\). Higher level → wider CI"],
      ["z-statistic","CI multiplier when \\(\\sigma\\) is known. \\(z_{95}\\) = 1.96; \\(z_{99}\\) = 2.58; \\(z_{90}\\) = 1.64"],
      ["t-statistic","CI multiplier when \\(\\sigma\\) is unknown (small sample). df = \\(N-1\\). Always larger than z"],
      ["Degrees of freedom (df)","\\(df = N-1\\) for one sample; \\(N_1+N_2-2\\) for two-sample comparison. Determines which t-value to use"],
      ["Pooled standard deviation (s_pooled)","\\(s_\\text{pooled} = \\sqrt{\\sum(N_i-1)s_i^2 / (\\sum N_i - k)}\\). Combined SD from k datasets with similar spread"],
      ["Null hypothesis","Assumption being tested (e.g. 'two means are equal'). Rejected if test statistic > critical value at chosen confidence level"],
      ["Type I error (false positive)","Rejecting a true null hypothesis. Probability = \\(\\alpha = 1 - \\text{CL}\\)"],
      ["Two-means comparison test","Reject null if \\(|\\bar{x}_1 - \\bar{x}_2| > t \\cdot s_\\text{pooled} \\cdot \\sqrt{(N_1+N_2)/(N_1 N_2)}\\); df = \\(N_1+N_2-2\\)"],
      ["Bias detection test","Reject null (no bias) if \\(|\\bar{x} - x_t| > t \\cdot s/\\sqrt{N}\\). Tests for systematic error vs a known true value"],
      ["Q-test (Dixon's test)","Outlier test: \\(Q = |x_q - x_\\text{neighbour}| / \\text{range}\\). Reject if \\(Q > Q_\\text{crit}\\). Sort data ascending first"],
      ["Outlier","Measurement far outside the dataset scatter. Must be tested with Q-test before discarding"],
      ["Q-test critical values (90% CL)","N=3: 0.941; N=4: 0.765; N=5: 0.642; N=6: 0.560; N=7: 0.507; N=8: 0.468; N=9: 0.437; N=10: 0.412"],
      ["s_pooled usage rule","Use \\(s_\\text{pooled}\\) as \\(\\sigma\\) estimate when all component SDs are similar and total pooled df ≥ 25"],
      ["Statistical significance","Result is significant at a given CL if the probability of observing it by chance is less than \\(\\alpha = 1 - \\text{CL}\\)"],
    ]
  },
  t3: {
    name: "Topic 3 — Gravimetric Analysis",
    terms: [
      ["Gravimetric analysis","Quantitative method based on mass measurement. Analyte isolated and weighed as a precisely characterised compound"],
      ["Precipitation gravimetry","Analyte converted to insoluble precipitate, filtered, dried/ignited, and weighed"],
      ["Volatilisation gravimetry","Volatile component (CO₂, H₂O) released and either the mass loss or mass gained by a trap is measured"],
      ["Electrogravimetry","Analyte electrodeposited onto a pre-weighed Pt electrode; mass gain gives amount deposited"],
      ["Thermogravimetric analysis (TGA)","Mass recorded continuously as sample is heated at controlled rate. Mass-loss steps reveal decomposition temperatures"],
      ["Derivative TGA (DTG)","First derivative of TGA curve. Peaks mark temperature of maximum mass-loss rate; separates overlapping events"],
      ["Precipitating agent","Reagent converting analyte to insoluble precipitate. Common: AgNO₃ (Cl⁻), BaCl₂ (SO₄²⁻), DMG (Ni²⁺)"],
      ["Gravimetric factor (GF)","\\(\\text{GF} = (a \\times M_\\text{analyte}) / (b \\times M_\\text{precipitate})\\). Converts precipitate mass to analyte mass"],
      ["8 steps of precipitation gravimetry","Weigh → Dissolve → Precipitate → Filter → Wash → Dry/ignite → Weigh → Calculate"],
      ["Digestion","Heating precipitate in mother liquor after formation to grow larger, purer crystals via Ostwald ripening"],
      ["Ostwald ripening","Small crystals dissolve and redeposit on larger ones; reduces surface area and coprecipitation"],
      ["Coprecipitation","Contamination of precipitate by unwanted species. Types: surface adsorption, occlusion, mechanical entrapment, post-precipitation"],
      ["Surface adsorption","Ions adsorb onto crystal surface; minimised by washing"],
      ["Occlusion","Impurities physically trapped inside crystal lattice during growth. Cannot be removed by washing"],
      ["Mechanical entrapment","Mother liquor trapped within precipitate; minimised by digestion"],
      ["Post-precipitation","Second precipitate nucleates on the primary precipitate during prolonged standing"],
      ["Mother liquor","Solution surrounding the precipitate. Contains excess precipitating agent and dissolved impurities"],
      ["Combustion analysis","Sample burned in O₂; H₂O trapped in Drierite, CO₂ in Ascarite. Mass gains give n(H) and n(C)"],
      ["Drierite (CaSO₄)","H₂O absorbent in combustion analysis. Mass gain = m(H₂O) → n(H)"],
      ["Ascarite (NaOH on silica)","CO₂ absorbent in combustion analysis. Mass gain = m(CO₂) → n(C)"],
      ["Calcination","Heating dried precipitate to high temperature to convert it to a stable, stoichiometric form"],
      ["Empirical formula determination","Calculate moles of each element from % composition, divide by smallest, round to integers"],
    ]
  },
  t4: {
    name: "Topic 4 — Spectroscopy",
    terms: [
      ["Electromagnetic radiation (EMR)","Energy propagated as oscillating electric and magnetic fields. Exhibits both wave and particle behaviour"],
      ["Wavelength (λ)","Distance between wave crests. Units: m, nm, cm. Related by \\(c = \\lambda\\nu\\)"],
      ["Frequency (υ)","Oscillations per second (Hz = s⁻¹). Does NOT change when light moves between media"],
      ["Wavenumber (ν̄)","\\(\\bar{\\nu} = 1/\\lambda\\) (cm⁻¹). Proportional to energy. Used in IR. Conversion: \\(\\bar{\\nu}(\\text{cm}^{-1}) = 10^7/\\lambda(\\text{nm})\\)"],
      ["Speed of light (c)","\\(c = 2.998 \\times 10^8\\) m s⁻¹ in vacuum. Changes in media but frequency and energy remain constant"],
      ["Photon energy (E)","\\(E = h\\nu = hc/\\lambda = hc\\bar{\\nu}\\). Planck's constant \\(h = 6.626 \\times 10^{-34}\\) J s. Higher frequency → higher energy"],
      ["Planck's constant (h)","\\(h = 6.626 \\times 10^{-34}\\) J Hz⁻¹. Links photon energy to frequency: \\(E = h\\nu\\)"],
      ["Radiation intensity (I)","\\(I = P/A = E\\Phi/A\\). P = power (W), A = area, Φ = photon flux (photons s⁻¹)"],
      ["Transmittance (T)","\\(T = I/I_0\\). Fraction of incident intensity transmitted. T = 1: no absorption; T = 0: complete absorption"],
      ["Percent transmittance (%T)","\\(\\%T = (I/I_0) \\times 100\\). Related to absorbance: \\(A = 2 - \\log(\\%T)\\)"],
      ["Absorbance (A)","\\(A = -\\log T = \\log(I_0/I) = \\varepsilon bc\\). Dimensionless and additive for multiple absorbers"],
      ["Beer-Lambert law","\\(A = \\varepsilon bc\\). Valid for monochromatic light and dilute solutions. Deviations at high concentration"],
      ["Molar absorptivity (ε)","Species-specific constant in Beer-Lambert. Units: L mol⁻¹ cm⁻¹. Maximum at \\(\\lambda_\\text{max}\\)"],
      ["Path length (b)","Length of sample traversed by light (cm). Usually 1 cm cuvette in Beer-Lambert"],
      ["λ_max","Wavelength of maximum \\(\\varepsilon\\). Best for measuring concentration: highest sensitivity, most linear Beer-Lambert behaviour"],
      ["Blank correction","\\(A_\\text{analyte} = -\\log(I_A/I_B)\\). Uses blank as \\(I_0\\) reference to remove solvent/cuvette contributions"],
      ["Standard addition method","\\(C_x = A_x / (A_\\text{spiked} - A_x) \\times C_\\text{spike}\\). Compensates for matrix effects when matrix cannot be replicated"],
      ["Direct comparison (method B/C)","\\(C_x = (A_x / A_\\text{std}) \\times C_\\text{std}\\). Cancels \\(\\varepsilon\\) and b; requires identical conditions"],
      ["Known ε method (method A)","\\(C = A/(\\varepsilon b)\\). Requires accurate knowledge of \\(\\varepsilon\\)"],
      ["Matrix effect","Influence of non-analyte sample components on the measurement signal. Standard addition compensates; external calibration may not"],
      ["Ground state","Lowest energy state. Electrons occupy ground state at room temperature"],
      ["Excited state","Higher energy state reached by absorbing a photon of energy = \\(\\Delta E\\). Energy levels are quantised"],
      ["Absorption","Photon absorbed → atom promoted to excited state. Occurs when photon energy = \\(\\Delta E\\)"],
      ["Emission","Excited atom releases a photon and returns to lower energy state. Basis of atomic emission spectroscopy"],
      ["Fluorescence","Rapid radiative emission after absorption (~ns lifetime). Emitted photon has longer wavelength than absorbed"],
      ["Phosphorescence","Delayed radiative emission (ms–s lifetime). Spin-forbidden transition. Basis of glow-in-the-dark materials"],
      ["Non-radiative relaxation","Energy dissipated as heat rather than a photon. Reduces fluorescence quantum yield"],
      ["Deuterium lamp","UV source (150–400 nm). Continuous spectrum. Standard UV source in spectrophotometers"],
      ["Tungsten-halogen lamp","Visible source (400–800 nm). Continuous blackbody emission. Standard Vis source"],
      ["Diffraction grating","Wavelength selector. Disperses by diffraction: \\(n\\lambda = d\\sin\\theta\\). Tunable by rotation"],
      ["Quartz cuvette","Transparent to UV and Vis (160–3000 nm). Required for UV measurements; glass/plastic only transmit Vis"],
      ["Photomultiplier tube (PMT)","Highly sensitive detector. Dynode cascade amplifies signal ~10⁶×. Range 150–1000 nm"],
      ["Single-beam spectrometer","Blank and sample measured sequentially. Simpler but susceptible to source drift"],
      ["Double-beam spectrometer","Beam split between sample and reference simultaneously. Compensates source fluctuation"],
      ["Nebulisation","Solution broken into fine aerosol for introduction into flame/plasma"],
      ["Desolvation","Solvent evaporated from aerosol droplets to produce dry solid particles before atomisation"],
      ["Atomisation","Solid particles vaporised to free gas-phase atoms. Required for atomic absorption/emission"],
      ["ICP-OES","Inductively Coupled Plasma OES. RF Ar plasma (6000–10,000 K). Multi-element; wide dynamic range"],
      ["Flame emission spectroscopy (FES)","Flame excites atoms for emission. Simpler, less sensitive than ICP-OES. Best for alkali metals"],
      ["Self-absorption","Emitted photons reabsorbed by ground-state atoms at high concentration → non-linearity in emission"],
      ["Calibration curve","Plot of instrument response vs known concentration for standards. Interpolate to find unknown"],
      ["Wave-particle duality","EMR behaves as wave (diffraction) and particle (photoelectric effect, discrete absorption)"],
    ]
  },
  t5: {
    name: "Topic 5 — Titrations in Analytical Chemistry",
    terms: [
      ["Titrimetric analysis (titration)","Determining analyte amount by measuring the volume of standard titrant for stoichiometric reaction"],
      ["Titrant","Reagent of precisely known concentration added from a burette"],
      ["Analyte (titrand)","The species being determined"],
      ["Equivalence point (EQ)","Point where stoichiometric amount of titrant has been added. Theoretical — not directly observable"],
      ["End point (EP)","Experimentally observed signal change marking titration termination. Should coincide with EQ"],
      ["Titration error","\\(E_t = V_\\text{EP} - V_\\text{EQ}\\). Positive = overtitrated; negative = undertitrated"],
      ["4 titration types","1-Neutralisation (acid-base), 2-Complexometric, 3-Precipitation, 4-Redox"],
      ["pH","\\(\\text{pH} = -\\log[\\text{H}_3\\text{O}^+]\\). Acidity measure. pH + pOH = 14 at 25°C"],
      ["pKa","\\(\\text{p}K_a = -\\log K_a\\). Lower pKa = stronger acid. At the half-equivalence point, pH = pKa. Indicator colour-change range: pKa ± 1"],
      ["Ion product of water (Kw)","\\(K_w = [\\text{H}_3\\text{O}^+][\\text{OH}^-] = 1.0 \\times 10^{-14}\\) at 25°C. Relates pH and pOH"],
      ["Strong acid","Completely dissociates: HCl, HNO₃, H₂SO₄, HClO₄. \\([\\text{H}_3\\text{O}^+] = C_\\text{acid}\\)"],
      ["Strong base","Completely dissociates: NaOH, KOH. \\([\\text{OH}^-] = C_\\text{base}\\)"],
      ["Weak acid (HA)","Partially dissociates: HA ⇌ H⁺ + A⁻. \\(K_a = [\\text{H}^+][\\text{A}^-]/[\\text{HA}]\\)"],
      ["Weak base (A⁻)","Partially accepts a proton: A⁻ + H₂O ⇌ HA + OH⁻. \\(K_b = K_w/K_a\\)"],
      ["Henderson-Hasselbalch equation","\\(\\text{pH} = \\text{p}K_a + \\log([\\text{A}^-]/[\\text{HA}])\\). At half-EQ: [A⁻]=[HA] → pH = pKa"],
      ["Half-equivalence point","\\(V_\\text{BOH} = \\tfrac{1}{2}V_\\text{EQ}\\). pH = pKa (weak acid). Point of maximum buffering capacity"],
      ["Buffer","Solution resisting pH change. Contains weak acid HA and conjugate base A⁻. Maintains pH in EDTA titrations"],
      ["Indicator","Weak acid/base with differently coloured acid and base forms. Colour change centred at pKa ± 1. Choose so pKa overlaps EQ pH"],
      ["Phenolphthalein","pKa 9.5; colourless → pink; pH 8.5–10.5. For weak acid/strong base or strong acid/strong base"],
      ["Bromothymol blue","pKa 7.3; yellow → blue; pH 6.3–8.3. For near-neutral equivalence points"],
      ["Methyl red","pKa 5.0; red → yellow; pH 4.0–6.0"],
      ["Bromophenol blue","pKa 4.1; yellow → blue-violet; pH 3.1–5.1. For strongly acidic equivalence points"],
      ["Equivalence point pH (strong/strong)","pH = 7 at 25°C. Neutral salt formed"],
      ["Equivalence point pH (weak acid/strong base)","pH > 7. \\(\\text{pH} = -\\log\\sqrt{K_w K_a / C_\\text{AB}}\\). Conjugate base A⁻ is weakly basic"],
      ["Polyprotic acid","Has multiple ionisable protons and multiple equivalence points. H₃PO₄: pKa1=2.16, pKa2=7.21, pKa3=12.32"],
      ["Complexometric titration","Metal ion titrated with chelating ligand. pM monitored; metallochromic indicator marks endpoint"],
      ["Chelate effect","Polydentate ligands form more stable complexes than equivalent monodentate ones. Driven by positive ΔS"],
      ["Denticity","Number of donor atoms in a ligand that simultaneously bind the metal. Mono(1), bi(2), tetra(4), hexa(6)"],
      ["Formation constant (Kf)","\\(K_f = [\\text{ML}]/([\\text{M}][\\text{L}])\\). Stability of metal-ligand complex. EDTA: \\(K_f\\)(Ca²⁺) = 5×10¹⁰; \\(K_f\\)(Fe³⁺) = 1.3×10²⁵"],
      ["Overall stability constant (βn)","\\(\\beta_n = K_1 K_2 \\cdots K_n\\). Product of all stepwise formation constants"],
      ["EDTA (H₄Y)","Hexadentate ligand (2N + 4O donors). Reacts 1:1 with ALL metal ions regardless of charge"],
      ["Y⁴⁻ (fully deprotonated EDTA)","Active form that complexes metals: M^n+ + Y⁴⁻ → MY^(n−4)+. Dominant above pH 10"],
      ["EDTA 1:1 ratio","EDTA always reacts 1:1 with metal ions regardless of charge — Ag⁺, Ca²⁺, Fe³⁺, Th⁴⁺ all consume 1 mol Y⁴⁻"],
      ["Eriochrome Black T (EBT)","Indicator for Ca²⁺/Mg²⁺ EDTA titrations at pH 10. Metal-EBT = red; free EBT = blue. Endpoint: red → blue"],
      ["Xylenol orange (XO)","Indicator for Zn²⁺, Pb²⁺, Bi³⁺ at pH 4–6. ZnXO = red; free XO = yellow. Endpoint: red → yellow"],
      ["Solubility product (Ksp)","\\(K_{sp} = [\\text{A}]^a[\\text{B}]^b\\) for A_aB_b(s) ⇌ aA + bB. Small Ksp → sparingly soluble"],
      ["Argentometric titration","Precipitation titration with AgNO₃. Precipitates Cl⁻, Br⁻, I⁻. Ksp(AgCl) = 1.8×10⁻¹⁰"],
      ["Volhard method","Back-titration for halides. Excess Ag⁺ added → AgX precipitated → excess Ag⁺ back-titrated with KSCN. Fe³⁺ indicator (FeSCN²⁺ = red at endpoint)"],
      ["Back-titration","Add known excess of primary reagent; titrate the excess with a second standard. Used when direct endpoint is difficult"],
      ["Conductometry (titration endpoint)","Conductivity monitored during titration. V-shaped minimum marks EQ in precipitation titrations"],
      ["Standard reduction potential (E⁰)","Tendency of species to be reduced vs SHE (= 0 V). \\(E^\\circ_\\text{rxn} = E^\\circ_\\text{red} - E^\\circ_\\text{ox} > 0\\) → spontaneous"],
      ["Redox half-reaction","Either oxidation (electron loss) or reduction (electron gain). Balance separately, then combine with equalised electrons"],
      ["KMnO₄/Fe²⁺ titration","MnO₄⁻ + 5Fe²⁺ + 8H⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O. Ratio 1:5. Self-indicating: first permanent purple = endpoint"],
      ["Dichromate/Fe²⁺ titration","Cr₂O₇²⁻ + 6Fe²⁺ + 14H⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O. Ratio 1:6. Diphenylamine sulfonate indicator"],
      ["Self-indicating titrant","Produces its own colour change at excess — no separate indicator needed. KMnO₄ is the prime example"],
      ["Diphenylamine sulfonate","Redox indicator for dichromate titrations. Colourless (reduced) → blue-green (oxidised by excess Cr₂O₇²⁻)"],
    ]
  }
}
